---
title: "Course Notes"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```

You can detail what you learned in the session within these pages. You can also use the Rmd markdown language and insert code chunks with `CMD/CTRL + SHIFT + I`.

# Session 1


# Session 2


# Session 3


# Session 4
Following session three, I spent time writing out the steps I might need to create one "Tidy" data frame that includes survey responses from each course. That looked like this:

##Pseudocode into Code
1. Read in various .csv files (all placed in common data folder)
2. Remove metadata headers...first two columns (repeat for each file)
3. Combine into one data frame
4. Isolate Likert-type items
5. Tidy data - gather into a longer table such that each response is its own entry

I then worked to write simplistic code to accomplish this task, which looked something like this:

> read_csv(“data/file_name1.csv”)

> file_name1_no_hd <- file_name1[-c(1,2), ]

> all_data <- rbind(file_name1_no_hd, file_name2_no_hd,...)

> all_likert <- all_data[ , -c(1:8, 10:17, 22, 29:38, 47, 49, 51, 53, 55, 57, 59, 61, 64:86)]

> all_likert <- gather(all_likert, key = "Question", value = "Response", -ResponseId)

I then worked to identify strategies to streamline this process. For the next session, I am hoping to make progress on writing 1 or more functions to expedite the data import process. Additionally, I am hoping to begin some preliminary visualization work.

# Session 5
Pulling data directly from Qualtrics (qualtRics package from rOpenSci) into project. Store private tokens in .Rprofile [usethis()]

Packages: usethis(); qualtRics(); gutenbergr()

# Session 6
The Chronicle of Higher Education just released a special report, [The Digital Campus: Big Data](https://www.chronicle.com/specialreport/The-Digital-Campus-Big-Data/105?cid=wcontentgrid_hp_1b). 

One of the articles touches on some interesting thoughtsaround data analytics and its relevance to the classroom, [Can Data Make You a Better Teacher?](https://www.chronicle.com/article/Can-Data-Make-You-a-Better/245597?cid=wsinglestory_hp_1a). Moreover, it references a number of projects supported by Indiana University's [Center for Learning Analytics and Student Success](https://class.indiana.edu/), which is hosting its 2nd Annual [Learning Analytics Summit](https://lasummit.indiana.edu/) this April.

# Session 7

# Session 8

# References