---
title: "Data Analysis in R: Research & Learning"
---

```{r, child="_setup.Rmd"}
```

## Project Overview

I am interested in automating the visualization and analysis process for the Online Summer Course Surveys. I would like to develop a project that can take new survey data each term (either directly from Qualtrics via an API or from downloaded .csv files) and quickly create a report. Portions of this project would include
1. A process to import and clean the data each term.
2. One or more standard visualizations of Likert-type item data.
3. Organization and/or parsing of open-ended text responses.
4. Report Template

## General Site Structure

We have provided a rough template for your website
- **course_notes.Rmd** - Write your notes for the class, try some code, work some exercises and use this as a virtual notepad for the items we review. This is a great way to showcase new skills and serve as a reference when you can't quite remember how you did something

- **pre_work.Rmd** - Use this document to complete any pre-work assignments.

- **project.Rmd** - As you might have guessed, use this section to write up your project

- **library.bib** - is text file that is available for you to put citations. You can then use these citations in the other Rmd documents. Also note that if you want to cite a package and want the bibtex you can do this by using the command `citation("packagename")`.

- **footer.html** - Go ahead and put your name in there!

When you are happy with what you have written for the day, go ahead and make a website out of it by using the following command in the console `rmarkdown::render_site()`

